### ISSUE TITLE
Photos from SD cards

### ISSUE THREAD

**Issue by Karry** [mholo65/harbour-filters#3]
Hi. It would be great to view photos even from SD card. Only images from internal memory are visible now.

**Comment by mholo65** [comment]
Hi @Karry and sorry for the late response. Unfortunately this project is not maintained anymore (as I don't use Sailfish), anyhow if you are interested in providing a PR I'll try to find a way for submitting a new version to the store.

Optimal would be if anyone in the Sailfish community would like to take the ownership for this application. Are you interested, or do you know anyone that could be?

**Comment by Karry** [comment]
Hi. 

I is sad to read that you are not using SFOS anymore... I can help with some features, but I don't want to commit myself to maintain another application :-) Beside it, I am not sure if harbour supports moving ownership of applications and it would be sad to create fork for such simple, but useful application. 

I would appreciate if you will able to upload new version. I can help with the testing...

**Comment by mholo65** [comment]
@Karry thank you! Yes, if you'll submit a PR (and possible provide me with binaries for Jolla harbour) I can create a new release and publish to store. If necessary, I can also reach out to Jolla staff about transferring harbour rights to another developer.

**Comment by bjorkstromm** [comment]
Fixed by #4
